export type UPDATE_GREETING = 'UPDATE_GREETING';
export type INCREMENT = 'INCREMENT';

export const  UPDATE_GREETING: UPDATE_GREETING = 'UPDATE_GREETING';
export const  INCREMENT: INCREMENT = 'INCREMENT';
